using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Clipper2Lib;
using Isoline.Gerber;

namespace Isoline.Toolpaths
{
	/// <summary>
	/// Turns the copper polygons of a Gerber layer into an isolation milling program.
	/// <para>
	/// This is the step that used to require a round trip through FlatCAM: load the Gerber
	/// there, offset it, export G-code, then bring that back into the sender to be height
	/// mapped. Doing it in-process means the toolpath, the height map and the machine all
	/// share one coordinate system and one preview.
	/// </para>
	/// <para>
	/// The geometry is a straight polygon offset: pass <c>n</c> is the copper outline
	/// inflated by <c>toolRadius + n * stepover * toolDiameter</c>, so the tool's edge just
	/// grazes the copper on the first pass and each further pass widens the trench.
	/// </para>
	/// </summary>
	public static class IsolationToolpathGenerator
	{
		/// <summary>
		/// Generates the offset contours for every pass, in cut order.
		/// Exposed separately from <see cref="Generate"/> so the UI can preview the
		/// geometry without building G-code text.
		/// </summary>
		public static List<PathsD> GenerateContours(PathsD copper, IsolationOptions options)
		{
			if (copper == null)
				throw new ArgumentNullException(nameof(copper));
			if (options == null)
				throw new ArgumentNullException(nameof(options));
			if (options.ToolDiameter <= 0)
				throw new ArgumentException("tool diameter must be positive", nameof(options));
			if (options.Passes < 1)
				throw new ArgumentException("at least one pass is required", nameof(options));

			List<PathsD> passes = new List<PathsD>(options.Passes);

			for (int pass = 0; pass < options.Passes; pass++)
			{
				double offset = options.ToolDiameter / 2
					+ pass * options.Stepover * options.ToolDiameter;

				PathsD inflated = Clipper.InflatePaths(copper, offset, JoinType.Round, EndType.Polygon, 2.0, 4);

				// Offsetting islands that sit close together produces overlapping outlines;
				// unioning collapses them into the single contour the tool can actually follow.
				inflated = Clipper.Union(inflated, FillRule.NonZero);

				if (options.Simplify > 0)
					inflated = Clipper.SimplifyPaths(inflated, options.Simplify);

				PathsD kept = new PathsD();

				foreach (PathD path in inflated)
				{
					if (path.Count < 3)
						continue;

					if (Math.Abs(Clipper.Area(path)) < options.MinimumContourArea)
						continue;

					kept.Add(path);
				}

				if (kept.Count > 0)
					passes.Add(kept);
			}

			return passes;
		}

		/// <summary>
		/// Generates a complete G-code program for the given copper geometry.
		/// </summary>
		public static List<string> Generate(PathsD copper, IsolationOptions options)
		{
			List<PathsD> passes = GenerateContours(copper, options);
			CultureInfo ci = CultureInfo.InvariantCulture;

			List<string> gcode = new List<string>
			{
				"(Isolation toolpath generated by Isoline)",
				string.Format(ci, "(tool {0:0.###} mm - {1} passes - stepover {2:0.##} - depth {3:0.###} mm)",
					options.ToolDiameter, options.Passes, options.Stepover, options.CutDepth),
				"G21 G90 G17 G94",
				string.Format(ci, "G0 Z{0:0.###}", options.SafeHeight),
			};

			if (options.SpindleSpeed > 0)
			{
				gcode.Add(string.Format(ci, "S{0:0} M3", options.SpindleSpeed));
				gcode.Add("G4 P2");     // spin-up dwell
			}

			PointD position = new PointD(0, 0);

			// The preamble already lifted to the safe height; tracking that avoids emitting a
			// redundant "G0 Z<safe>" before the very first contour (a zero length move that
			// some controllers warn about and that shows up as a stutter on others).
			bool atSafeHeight = true;
			bool positionKnown = false;

			for (int passIndex = 0; passIndex < passes.Count; passIndex++)
			{
				gcode.Add(string.Format(ci, "(pass {0} of {1})", passIndex + 1, passes.Count));

				List<PathD> contours = passes[passIndex].ToList();

				if (options.OptimiseTravel)
					contours = OrderForShortTravel(contours, position);

				foreach (PathD contour in contours)
				{
					PathD path = StartAtNearest(contour, position);

					if (!atSafeHeight)
						gcode.Add(string.Format(ci, "G0 Z{0:0.###}", options.SafeHeight));

					if (!positionKnown || DistanceSquared(position, path[0]) > 1e-12)
						gcode.Add(string.Format(ci, "G0 X{0:0.####} Y{1:0.####}", path[0].x, path[0].y));

					gcode.Add(string.Format(ci, "G1 Z{0:0.###} F{1:0.###}", options.CutDepth, options.PlungeRate));
					atSafeHeight = false;
					gcode.Add(string.Format(ci, "F{0:0.###}", options.FeedRate));

					for (int i = 1; i < path.Count; i++)
						gcode.Add(string.Format(ci, "G1 X{0:0.####} Y{1:0.####}", path[i].x, path[i].y));

					// close the loop
					gcode.Add(string.Format(ci, "G1 X{0:0.####} Y{1:0.####}", path[0].x, path[0].y));

					position = path[0];
					positionKnown = true;
				}
			}

			if (!atSafeHeight)
				gcode.Add(string.Format(ci, "G0 Z{0:0.###}", options.SafeHeight));

			if (options.SpindleSpeed > 0)
				gcode.Add("M5");

			gcode.Add("M30");

			return gcode;
		}

		/// <summary>
		/// Greedy nearest-neighbour ordering of the contours.
		/// <para>
		/// A board of a few hundred pads can spend more time in rapids than in the cut if
		/// the contours are traced in the order the Gerber happened to list them. Greedy
		/// nearest neighbour is not optimal - this is a travelling salesman problem - but it
		/// is O(n^2) with a tiny constant and typically removes most of the wasted travel.
		/// </para>
		/// </summary>
		private static List<PathD> OrderForShortTravel(List<PathD> contours, PointD start)
		{
			List<PathD> remaining = new List<PathD>(contours);
			List<PathD> ordered = new List<PathD>(contours.Count);
			PointD current = start;

			while (remaining.Count > 0)
			{
				int bestIndex = 0;
				double bestDistance = double.MaxValue;

				for (int i = 0; i < remaining.Count; i++)
				{
					double distance = NearestVertexDistance(remaining[i], current);

					if (distance < bestDistance)
					{
						bestDistance = distance;
						bestIndex = i;
					}
				}

				PathD next = remaining[bestIndex];
				remaining.RemoveAt(bestIndex);
				ordered.Add(next);

				PathD entered = StartAtNearest(next, current);
				current = entered[0];
			}

			return ordered;
		}

		/// <summary>
		/// Rotates a closed contour so that it begins at the vertex closest to where the
		/// tool already is. The cut is identical either way, the rapid into it is shorter.
		/// </summary>
		private static PathD StartAtNearest(PathD contour, PointD from)
		{
			int best = 0;
			double bestDistance = double.MaxValue;

			for (int i = 0; i < contour.Count; i++)
			{
				double distance = DistanceSquared(contour[i], from);

				if (distance < bestDistance)
				{
					bestDistance = distance;
					best = i;
				}
			}

			if (best == 0)
				return contour;

			PathD rotated = new PathD(contour.Count);

			for (int i = 0; i < contour.Count; i++)
				rotated.Add(contour[(best + i) % contour.Count]);

			return rotated;
		}

		private static double NearestVertexDistance(PathD contour, PointD from)
		{
			double best = double.MaxValue;

			foreach (PointD p in contour)
				best = Math.Min(best, DistanceSquared(p, from));

			return best;
		}

		private static double DistanceSquared(PointD a, PointD b)
		{
			double dx = a.x - b.x;
			double dy = a.y - b.y;

			return dx * dx + dy * dy;
		}
	}
}
